- name: Install latest version of "aptitude"
  apt:
    name: "aptitude"
    state: latest
    force_apt_get: true

- name: installing repo for Java 8 in Ubuntu
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

