
- name: waiting for localhost status to be 200
  uri:
    url: http://localhost:8888
    return_content: yes
  register: result
  until: result['status']  == 200
  retries: 20
  delay: 30


- name: verify API status
  uri:
    url: http://localhost:8888
    return_content: yes
  register: result
  until: result['content'] | from_json |json_query('status') == "alive"
  retries: 0
