- name: copy service to /etc/systemd/system/webapp.service
  copy: src=upload/webapp.service dest=/etc/systemd/system/webapp.service


- name: Changing perm of "/opt/spring/run.sh", adding "+x"
  file: dest=/opt/spring/run.sh mode=a+x

- name: restart service webapp and issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: webapp
    enabled: true


- name: waiting for localhost status to be 200
  uri:
    url: http://localhost
    return_content: yes
  register: result
  until: result['status']  == 200
  retries: 20
  delay: 30


- name: verify API status
  uri:
    url: http://localhost
    return_content: yes
  register: result
  until: result['content'] | from_json |json_query('status') == "alive"
  retries: 0
