- name: copy service to /etc/systemd/system/webapp.service
  copy: src=upload/webapp.service dest=/etc/systemd/system/webapp.service


- name: Ensure "/opt/spring/run.sh" is executable
  file: dest=/opt/spring/run.sh mode=a+x

- name: restart service webapp and issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: webapp
    enabled: true

